GET http://localhost:8082/api/drivers
###

GET http://localhost:8082/api/drivers/5
###

POST http://localhost:8082/api/drivers
Content-Type: application/json

{
  "name": "Carlos Sainz",
  "wins": 0,
  "championships": 0
}
###

PUT http://localhost:8082/api/drivers/5
Content-Type: application/json

{
  "name": "Carlos Sainz",
  "wins": 1,
  "championships": 0
}
###

DELETE http://localhost:8082/api/drivers/5
###







GET http://localhost:8082/api/teams/scuderia_ferrari/drivers
###

GET http://localhost:8082/api/teams/scuderia_ferrari/drivers/5
###

POST http://localhost:8082/api/teams/scuderia_ferrari/drivers
Content-Type: application/json

{
  "name": "Carlos Sainz",
  "wins": 0,
  "championships": 0
}
###

#PUT http://localhost:8081/api/teams/scuderia_ferrari/drivers/5
#Content-Type: application/json
#
#{
#  "name": "Carlos Sainz",
#  "wins": 1,
#  "championships": 0
#}
###

DELETE http://localhost:8082/api/teams/scuderia_ferrari
###
