GET http://localhost:8080/api/drivers
###

GET http://localhost:8080/api/drivers/5
###

POST http://localhost:8080/api/drivers
Content-Type: application/json

{
  "name": "Carlos Sainz",
  "wins": 0,
  "championships": 0
}
###

#PUT http://localhost:8080/api/drivers/5
#Content-Type: application/json
#
#{
#  "name": "Carlos Sainz",
#  "wins": 1,
#  "championships": 0
#}
###

#DELETE http://localhost:8080/api/drivers/5
###





GET http://localhost:8080/api/teams
###

GET http://localhost:8080/api/teams/alpine
###

POST http://localhost:8080/api/teams
Content-Type: application/json

{
  "name": "alpine",
  "wins": 145,
  "championships": 2
}
###

#PUT http://localhost:8080/api/teams/alpine
#Content-Type: application/json
#
#{
#  "wins": 156,
#  "championships": 3
#}
###

DELETE http://localhost:8080/api/teams/alpine
###





GET http://localhost:8080/api/teams/alpine/drivers
###

GET http://localhost:8080/api/teams/alpine/drivers/5
###

POST http://localhost:8080/api/teams/alpine/drivers
Content-Type: application/json

{
  "name": "Carlos Sainz",
  "wins": 0,
  "championships": 0
}
###

#PUT http://localhost:8080/api/teams/alpine/drivers/5
#Content-Type: application/json
#
#{
#  "name": "Carlos Sainz",
#  "wins": 1,
#  "championships": 0
#}
###

#DELETE http://localhost:8080/api/teams/alpine/drivers/5
###
