GET http://localhost:8081/api/teams
###

GET http://localhost:8081/api/teams/alpine
###

POST http://localhost:8081/api/teams
Content-Type: application/json

{
  "name": "alpine",
  "wins": 145,
  "championships": 2
}
###

#PUT http://localhost:8081/api/teams/alpine
#Content-Type: application/json
#
#{
#  "wins": 156,
#  "championships": 3
#}
###

DELETE http://localhost:8081/api/teams/alpine
###
